[project]
name = ""
version = "0.0.1"
dependencies = [
    "requests>=2.28",
    "pandas>=2.0",
    "pyarrow",
    "python-dotenv",
    "tqdm",
    "matplotlib",
    "jupyterlab",
    "scikit-learn",
    "pytest"
]
requires-python = ">=3.10,<3.11"

[tool.uv]
package = false
