bet_type: btts
elo_k_factor: 25
elo_home_advantage: 100.0
form_window: 12
ema_span: 16
poisson_lookback: 17
half_life_days: 60.0
h2h_matches: 5
goal_diff_lookback: 5
home_away_form_window: 5
fouls_ema_span: 10
cards_ema_span: 10
shots_ema_span: 10
corners_ema_span: 10
fouls_window_sizes:
- 5
- 10
cards_window_sizes:
- 5
- 10
shots_window_sizes:
- 5
- 10
corners_window_sizes:
- 5
- 10
- 20
optimized: true
optimization_date: '2026-01-25T15:53:37.865239'
precision: 0.5850110779535196
roi: 46.25276948837991
n_trials: 2
